# nixpacks.toml
# Configure system package dependencies and shared library links.

[phases.setup]
nixPkgs = [
    "...",
    "xorg.libxcb",
    "libGL",
    "libGLU",
    "glib",
    "xorg.libX11",
    "xorg.libXext",
    "xorg.libXrender"
]
nixLibs = [
    "...",
    "xorg.libxcb",
    "libGL",
    "libGLU",
    "glib",
    "xorg.libX11",
    "xorg.libXext",
    "xorg.libXrender"
]

[phases.install]
cmds = [
    "python -m venv .venv",
    ".venv/bin/pip install --upgrade pip",
    ".venv/bin/pip install -r requirements.txt",
    ".venv/bin/pip uninstall -y opencv-python opencv-python-headless",
    ".venv/bin/pip install opencv-python-headless"
]
